### ISSUE TITLE
access_token

### ISSUE THREAD

**Issue by the-mace** [gglockner/teslajson#5]
Hi there, in the prior version of the library it was possible to access the Connection.access_token value which allowed for caching of the access token for extended periods and allowed me to pass it back in later. The recent changes broke that interface (access_token no longer there) and prohibits caching of the token.

**Comment by gglockner** [comment]
I could consider exposing the access_token, but that opens up a different problem: the access_token is not valid forever.  In the latest version, I now save the expiration of the access_token, so that it will be persisted only while it is valid.  If it has expired, it gets refreshed automatically.  This was needed to support an application where the Connection object may be retained for weeks or even months.

The cleaner way is for you to save the Connection object.  If your application needs to quit and restore the Connection object, why not pickle it?

**Comment by the-mace** [comment]
The assumption is you're always calling connect with the email and
password. But if anyone uses this library for a site supporting multiple
users and does not want to save passwords then this library cannot be used
in its current form. Saving picked objects for all those users vs a small
token isn't very scalable.

**Comment by gglockner** [comment]
Fixed in commit 4e5fc2223e1bee7edb202f50345130f3f5bed956
