### ISSUE TITLE
This library is used for harvesting Tesla login credentials?

### ISSUE THREAD

**Issue by lauritzen** [gglockner/teslajson#7]
It is, to say the least, extremely suspicious that this library gets the Tesla API base URL from [a pastbin.com URL](https://pastebin.com/0a8e0xTJ) managed by the maintainer (@gglockner). This would suggest that all login credentials from the clients using this can be relayed to anywhere he wants. 

https://github.com/gglockner/teslajson/blob/e91d78739341dad019430cd4e69962ad653d9261/teslajson.py#L56
  
For this reason I would advise caution using it and at least fork and modify the code.

**Comment by gglockner** [comment]
Let me explain why it uses an external URL.  I originally wrote the teslajson library with the URL hard-coded (ex: https://github.com/gglockner/teslajson/commit/dc0dd53854675fd46fbd80e8eac158605bbdf968).  However, this API is not officially supported by Tesla, and could change at any time.  So if Tesla breaks the URL, I would need to update the library and anything that uses the library would need to be updated as well.  So I refactored this to use Pastebin, so that the URL and the ID/secret could be updated without having to update the teslajson library.  This is why I pull info from the external URL on Pastebin.

However, I get your point about security.  What about the following compromise: what if the library checks for tampering in the URL, so it will throw an exception if Pastebin returns a base URL that is not something like *.tesla.com or *.teslamotors.com?  If you want to code this and submit a pull request, I'm happy to review and approve it.  Otherwise I could work on it in a few days (since teslajson is a hobby project that I only touch when I have a few minutes).

**Comment by lauritzen** [comment]
I see. Well I think it would be safe to assume that if Tesla changes it's webservice endpoint or protocol version that the library would need updating anyway, so I'd much prefer hardcoded values within the code.

**Comment by TaylorSMarks** [comment]
Good catch. I had thought "I should check that my credentials are only being sent to Tesla", and I actually did look at the source a bit, and then I thought, "He's probably doing the right thing. I'm bored. I want to start using this API already!" and I never actually caught this.

Anyways... I start with the assumption people are good. I've always done that, and its never caused me much trouble. Until proven otherwise, I'll assume gglockner is a good person. My only real concern is that if a bad person managed to get into his pastebin and changed where that URL points.

Well, and I'm a bit concerned that maybe a bad actor will try making a malicious pull request that compromises your password and gglockner doesn't notice... but that wouldn't impact me directly, since I'm unlikely to actually update my copy of this library unless there's a bug that impacts me or a new feature I want...

**Comment by OverloadUT** [comment]
@gglockner Would you accept a PR to change this to be hardcoded? I don't agree that the compromise is good enough from a security perspective.

(I am happy to fork instead if you'd like to stick with the flexible option; just let me know)
